name: steam
summary: Launcher for the Steam software distribution service
description: |
 Steam is a software distribution service with an online store, automated
 installation, automatic updates, achievements, SteamCloud synchronized
 savegame and screenshot functionality, and many social features.

adopt-info: steam

grade: stable
confinement: strict
architectures:
  - build-on: amd64

base: core20

layout:
  /usr/lib/steam:
    bind: $SNAP/lib/steam

plugs:
  steam-library:
    interface: personal-files
    write:
      - $HOME/.local/share/Steam
      - $HOME/Steam

environment:
  LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$SNAP/usr/lib/i386-linux-gnu/pulseaudio

parts:
  launcher:
    plugin: nil
    source : ./src
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp steam-snap.sh $SNAPCRAFT_PART_INSTALL/bin

  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  steam:
    after: [ enable-i386 ]
    plugin: nil
    source: http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
    build-packages:
      - dpkg-dev
    stage-packages:
      - pciutils
      - xz-utils
      - zenity
      - on amd64:
          - libasound2:i386
          - libasound2-plugins:i386
          - libbsd0:i386
          - libc6:i386
          - libcurl4:i386
          - libdrm2:i386
          - libfreetype6:i386
          - libgcc1:i386
          - libgdk-pixbuf2.0-0:i386
          - libgl1:i386
          - libgl1-mesa-dri:i386
          - libglib2.0-0:i386
          - libglx-mesa0:i386
          - libgnutls30:i386
          - libgtk2.0-0:i386
          - libopenal1:i386
          - libopengl0:i386
          - libpulse0:i386
          - libstdc++6:i386
          - libva2:i386
          #- libva-wayland1:i386
          #- libva-x11-1:i386
          - libvdpau1:i386
          - libvulkan1:i386
          - libx11-6:i386
          - libxau6:i386
          - libxcb1:i386
          - libxdmcp6:i386
          - libxrandr2:i386
          - libxtst6:i386
          - mesa-vdpau-drivers:i386
          - mesa-vulkan-drivers:i386
          - va-driver-all:i386

    override-build: |
      # Set the snap version from the .deb package version
      snapcraftctl set-version $(dpkg-parsechangelog -l usr/share/doc/steam-launcher/changelog.all.gz -S Version)
      # Copy the binaries and data
      cp -a usr/bin $SNAPCRAFT_PART_INSTALL/bin
      cp -a usr/lib/* $SNAPCRAFT_PART_INSTALL/lib/
      cp -a usr/share/doc/steam $SNAPCRAFT_PART_INSTALL/doc
      # Copy over the icon
      cp usr/share/icons/hicolor/256x256/apps/steam.png $SNAPCRAFT_PART_INSTALL/steam.png
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui
      ln -s ../../steam.png $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      # Install the desktop file, with the icon field munged
      sed 's|Icon=steam|Icon=${SNAP}/steam.png|g' usr/share/applications/steam.desktop > $SNAPCRAFT_PART_INSTALL/steam.desktop

apps:
  steam:
    extensions: [ gnome-3-38 ]
    command: bin/steam-snap.sh
    desktop: steam.desktop
    environment:
      HOME: $SNAP_USER_COMMON
      LIBGL_DEBUG: verbose
    plugs:
      - hardware-observe
      - joystick
      - network
      - opengl
      - audio-playback
      - audio-record
